version: '3.8'

services:
  proxy:
    build: .
    container_name: 3proxy_via_stunnel
    restart: unless-stopped
    network_mode: host
    environment:
      - DOMAIN=quasar.domain.com
      - PROXY_EXT_IP=XXX.YYY.ZZZ.WWW
      - PROXY_INT_IP=XXX.YYY.ZZZ.WWW
      - PROXY_PORT_HTTPS=443
      - PROXY_PORT_HTTP=3218
#example:
# user:CL:pass
# user:CL:pass user2:CL:pass2
# $/etc/3proxy/users.lst
      - PROXY_USER_LIST=user:CL:upper! user2:CL:supper
    volumes:
      - ./certs:/etc/letsencrypt
